package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.jdbcdemo.domain.Archive;
import com.example.jdbcdemo.domain.Resource;

public class ResourceManager {
	private Connection connection;
	private Statement statement;
	
	private PreparedStatement addResourceStmt;
	private PreparedStatement updateResourceToArchiveStmt;
	private PreparedStatement addArchiveStmt;
	private PreparedStatement getAllArchivesStmt;
	private String createResourceTable = "CREATE TABLE Resource(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(20), author varchar(20), date integer, teamnumber integer)";
	private PreparedStatement getAllResourcesStmt;
	private PreparedStatement deleteAllResourcesStmt;
	private PreparedStatement deleteAllArchivesStmt;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	public ResourceManager() {
		super();
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Resource".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			if (!tableExists)
				statement.executeUpdate(createResourceTable);
			
			addResourceStmt = connection.prepareStatement("INSERT INTO Resource (name, author, date) VALUES (?,?,?)");
			updateResourceToArchiveStmt = connection.prepareStatement("UPDATE Resource SET teamnumber = ? WHERE name = ? ");
			addArchiveStmt = connection.prepareStatement("INSERT INTO Archive (name, teamNumber, phone) VALUES (?,?,?)");
			getAllArchivesStmt = connection
					.prepareStatement("SELECT id, name, teamNumber, phone From Archive");
			getAllResourcesStmt = connection.prepareStatement("SELECT id, name, author, date, teamnumber FROM Resource");
			deleteAllArchivesStmt = connection
					.prepareStatement("DELETE FROM Archive");
			deleteAllResourcesStmt = connection.prepareStatement("DELETE FROM Resource");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	public Connection getConnection() {
		return connection;
	}
	public void setConnection(Connection connection) {
		this.connection = connection;
	}
	public Statement getStatement() {
		return statement;
	}
	public void setStatement(Statement statement) {
		this.statement = statement;
	}
	public PreparedStatement getAddResourceStmt() {
		return addResourceStmt;
	}
	public void setAddResourceStmt(PreparedStatement addResourceStmt) {
		this.addResourceStmt = addResourceStmt;
	}
	public String getCreateResourceTable() {
		return createResourceTable;
	}
	public void setCreateResourceTable(String createResourceTable) {
		this.createResourceTable = createResourceTable;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	
	public int addResource(Resource resource){
		int count = 0;
		try {
			addResourceStmt.setString(1, resource.getName());
			addResourceStmt.setString(2, resource.getAuthor());
			addResourceStmt.setInt(3, resource.getDate());
			count = addResourceStmt.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return count;
	}
	public void clearResources() {
		try {
			deleteAllResourcesStmt.executeUpdate();
			deleteAllArchivesStmt.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public int countRows(){
		int count = 0;
		try {
			ResultSet rs = getAllResourcesStmt.executeQuery();
			while (rs.next()){
				count++;
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return count;
	}
	
	public List<Resource> getAllResources() {
		List<Resource> resources = new ArrayList<Resource>();
		try {
			ResultSet rs = getAllResourcesStmt.executeQuery();
			while (rs.next()){
				Resource r = new Resource();
				r.setId(rs.getInt("id"));
				r.setName(rs.getString("name"));
				r.setAuthor(rs.getString("author"));
				r.setDate(rs.getInt("date"));
				r.setTeamNumber(rs.getInt("teamnumber"));
				resources.add(r);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return resources;
	}
	
	public int addResourceToArchive(Resource r, Archive a) {
		int count = 0;
		int resourceExists = 0;
		try {
		connection.setAutoCommit(true); // true - kazda transakcja osobna
		ResultSet rsA = getAllResourcesStmt.executeQuery();
		while (rsA.next()){
			if((r.getName()).equals(rsA.getString("name"))){
				resourceExists = 1;
				System.out.println("ResourceExists");
				break;
			}
		}
		if( resourceExists == 1 ){
			ResultSet rs = getAllArchivesStmt.executeQuery();
			while (rs.next()){
				Archive tmpA = new Archive();
				tmpA.setTeamNumber(rs.getInt("teamNumber"));
				if(((Integer)tmpA.getTeamNumber()).equals(a.getTeamNumber())){
					updateResourceToArchiveStmt.setInt(1, a.getTeamNumber());
					updateResourceToArchiveStmt.setString(2, r.getName());
					System.out.println(updateResourceToArchiveStmt);
					count = updateResourceToArchiveStmt.executeUpdate();
				}
			}
		}
		else {
			try {
				addResourceStmt.setString(1, r.getName());
				addResourceStmt.setString(2, r.getAuthor());
				addResourceStmt.setInt(3, r.getDate());
				addResourceStmt.executeUpdate();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		if (count == 0){
				addArchiveStmt.setString(1, a.getName());
				addArchiveStmt.setInt(2, a.getTeamNumber());
				addArchiveStmt.setString(3, a.getPhone());
				addArchiveStmt.executeUpdate();
				System.out.println(addArchiveStmt);
				updateResourceToArchiveStmt.setInt(1, a.getTeamNumber());
				updateResourceToArchiveStmt.setString(2, r.getName());
				System.out.println(updateResourceToArchiveStmt);
				count = updateResourceToArchiveStmt.executeUpdate();
			
		}
		connection.commit();
		} catch (SQLException e) {
			try {
				connection.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
		return count;
	}
}
